<?php
/**
 * File Name: Delete.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 13:16:58
 * @version: 4.0.4
 */

namespace qh4module\rabc\models\role;


use qh4module\rabc\models\BkRelationUserRoleActiveRecord;
use qh4module\rabc\models\BkRoleActiveRecord;
use qh4module\rabc\models\BkRoleModel;
use qh4module\rabc\models\BkRoleRelationActiveRecord;
use qh4module\rabc\models\RabcRedis;
use QTTX;

/**
 * Class Delete
 * 从tbl_bk_role表的删除数据
 * @package qh4module\rabc\models\role
 */
class Delete extends BkRoleModel
{
    /**
     * @var string[]|int[] 接收参数,必须：主键
     */
    public $ids;
    
    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [['ids'],'required'],
            [['ids'], 'array', 'type' => function ($value) {
                return is_string($value) || is_numeric($value);
            }],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        $db = QTTX::$app->db;

        $db->beginTrans();

        try {

            $result = BkRoleActiveRecord::find($db)
                ->whereIn('id', $this->ids)
                ->all();
            if (empty($result)) {
                $this->addError('ids', '删除的条目不存在');
                return false;
            }

            /**
             * @var $item BkRoleActiveRecord
             */
            foreach ($result as $item) {
                if ($item->is_fixed == 1) {
                    $this->addError('ids', '存在禁止删除的角色');
                    return false;
                }
                // 伪删除
                $item->del_time = time();
                $item->update($db);
            }

            // 删除所有关联关系
            $db->update(BkRoleRelationActiveRecord::tableName())
                ->col('del_time', time())
                ->whereIn('role_id', $this->ids)
                ->where('del_time=0')
                ->query();

            $db->update(BkRoleRelationActiveRecord::tableName())
                ->col('del_time', time())
                ->whereIn('parent_id', $this->ids)
                ->where('del_time=0')
                ->query();

            // 删除用户的关联
            $db->update(BkRelationUserRoleActiveRecord::tableName())
                ->col('del_time', time())
                ->whereIn('role_id', $this->ids)
                ->where('del_time=0')
                ->query();

            // 清理缓存
            RabcRedis::clearRedis();

            $db->commitTrans();

            return true;

        } catch (\Exception $exception) {
            $db->rollBackTrans();
            
            throw $exception;
        }
    }
}
