<?php
/**
 * File Name: Detail.php
 * Automatically generated by QGC tool
 * @date: 2021-04-21 11:09:02
 * @version: 4.0.4
 */

namespace qh4module\rabc\models\user;


use qh4module\city\models\CityActiveRecord;
use qh4module\rabc\models\BkRelationUserRoleActiveRecord;
use qh4module\rabc\models\BkRoleActiveRecord;
use qh4module\rabc\models\BkUserActiveRecord;
use qh4module\rabc\models\BkUserInfoActiveRecord;
use qh4module\rabc\models\BkUserModel;

/**
 * Class Detail
 * 获取tbl_bk_user表的单条数据详细信息
 * @package qh4module\rabc\models\models\user
 */
class Detail extends BkUserModel
{
    /**
     * @var string|int 接收参数,必须：主键
     */
    public $id;

    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        // 所有的字段,根据需要删减
        $fields = ['`ta`.`id`', '`ta`.`account`', '`ta`.`mobile`', '`ta`.`email`',
            '`ta`.`password`', '`ta`.`salt`', '`ta`.`create_by`',
            '`ta`.`create_time`', '`ta`.`wechat_unionid`',
            '`ta`.`wechat_openid`', '`ta`.`qq_id`', '`ta`.`alipay_id`',
            '`ta`.`weibo_id`', '`ta`.`apple_id`', '`ta`.`state`',
            '`tb`.`nick_name`', '`tb`.`avatar`', '`tb`.`gender`', '`tb`.`birthday`',
            '`tb`.`description`', '`tb`.`city_id`',
            'tc.nick_name as create_by_name','td.name as city_name'
        ];

        $tb_info = BkUserInfoActiveRecord::tableName();
        $tb_city = CityActiveRecord::tableName();
        $result = BkUserActiveRecord::find()
            ->select($fields)
            ->leftJoin("$tb_info as tb", 'ta.id=tb.user_id')
            ->leftJoin("$tb_info as tc", 'ta.create_by=tc.user_id')
            ->leftJoin("$tb_city as td",'tb.city_id=td.id')
            ->whereArray(['ta.id' => $this->id])
            ->asArray()
            ->one();
        if (empty($result)) {
            $this->addError('id', '查询条目不存在');
            return false;
        }

        // 获取关联角色
        $result['role_ids'] = \QTTX::$app->db
            ->select(['role_id'])
            ->from(BkRelationUserRoleActiveRecord::tableName())
            ->whereArray(['user_id' => $this->id])
            ->where('del_time=0')
            ->column();

        // 获取角色详细
        if (empty($result['role_ids'])) {
            $result['roles'] = [];
        }else{
            $result['roles'] = \QTTX::$app->db
                ->select(['id', 'name'])
                ->from(BkRoleActiveRecord::tableName())
                ->whereIn('id', $result['role_ids'])
                ->where('del_time=0')
                ->query();
        }

        return $result;
    }
}
