<?php
/**
 * File Name: Create.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 17:50:12
 * @version: 4.0.4
 */

namespace qh4module\rabc\models\privilege;


use qttx\helper\ArrayHelper;
use qh4module\rabc\models\BkPrivilegeActiveRecord;
use qh4module\rabc\models\BkPrivilegeModel;
use qh4module\token\TokenFilter;
use QTTX;

/**
 * Class Create
 * tbl_bk_privilege表新增一条数据
 * @package qh4module\rabc\models\privilege
 */
class Create extends BkPrivilegeModel
{
    
    /**
     * @var string 接收参数,必须：上级
     */
    public $parent_id;

    /**
     * @var string 接收参数,必须：唯一标记
     */
    public $key;

    /**
     * @var string 接收参数,必须：名称
     */
    public $name;

    /**
     * @var string 接收参数,非必须：说明
     */
    public $desc;

    /**
     * @var int 接收参数,必须：类型 
     */
    public $type;

    /**
     * @var int 接收参数,必须：级别
     */
    public $level;

    /**
     * @var string 接收参数,非必须：图标
     */
    public $icon;

    /**
     * @var string 接收参数,必须：关联的路由
     */
    public $path;

    /**
     * @var int 接收参数,必须：排序
     */
    public $sort;


    /**
     * @inheritDoc
     */
    public function rules()
    {
        return ArrayHelper::merge([
            [['parent_id','key','name','type','level','path','sort'],'required']
        ], parent::rules());
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        $model = new BkPrivilegeActiveRecord();
        $id = QTTX::$app->snowflake->id();
		$model->id = $id;
		$model->parent_id = $this->parent_id;
		$model->id_path = '';
		$model->key = $this->key;
		$model->key_path = '';
		$model->name = $this->name;
		$model->desc = $this->desc;
		$model->type = $this->type;
		$model->level = $this->level;
		$model->icon = $this->icon;
		$model->path = $this->path;
		$model->create_time = time();
		$model->create_by = TokenFilter::getPayload('user_id');
		$model->sort = $this->sort;
		$model->del_time = 0;
    
        return $model->insert();
    }
}