<?php
/**
 * File Name: Delete.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 17:50:12
 * @version: 4.0.4
 */

namespace qh4module\rabc\models\privilege;


use qh4module\rabc\models\BkPrivilegeActiveRecord;
use qh4module\rabc\models\BkPrivilegeModel;
use QTTX;

/**
 * Class Delete
 * 从tbl_bk_privilege表的删除数据
 * @package qh4module\rabc\models\privilege
 */
class Delete extends BkPrivilegeModel
{
    /**
     * @var string[]|int[] 接收参数,必须：主键
     */
    public $ids;
    
    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [['ids'],'required'],
            [['ids'], 'array', 'type' => function ($value) {
                return is_string($value) || is_numeric($value);
            }],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        $db = QTTX::$app->db;

        $db->beginTrans();

        try {

            $result = BkPrivilegeActiveRecord::find($db)
                ->whereIn('id', $this->ids)
                ->all();
            if (empty($result)) {
                $this->addError('ids', '删除的条目不存在');
                return false;
            }

            /**
             * @var $item BkPrivilegeActiveRecord
             */
            foreach ($result as $item) {
                // 伪删除
                $item->del_time = time();
                $item->update($db);
            }

            $db->commitTrans();

            return true;

        } catch (\Exception $exception) {
            $db->rollBackTrans();
            
            throw $exception;
        }
    }
}
