<?php
/**
 * File Name: Detail.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 17:50:12
 * @version: 4.0.4
 */

namespace qh4module\rabc\models\privilege;


use qh4module\rabc\models\BkPrivilegeActiveRecord;
use qh4module\rabc\models\BkPrivilegeModel;
use qh4module\rabc\models\BkRelationRolePrivilegeActiveRecord;
use qh4module\rabc\models\BkRoleActiveRecord;
use qh4module\rabc\models\BkUserInfoActiveRecord;

/**
 * Class Detail
 * 获取tbl_bk_privilege表的单条数据详细信息
 * @package qh4module\rabc\models\privilege
 */
class Detail extends BkPrivilegeModel
{
    /**
     * @var string|int 接收参数,必须：主键
     */
    public $id;
    
    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [['id'],'required'],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        // 所有的字段,根据需要删减
        $fields = ['`ta`.`id`','`ta`.`parent_id`','`ta`.`id_path`','`ta`.`key`','`ta`.`key_path`',
            '`ta`.`name`','`ta`.`desc`','`ta`.`type`','`ta`.`level`','`ta`.`icon`','`ta`.`path`',
            '`ta`.`create_time`','`ta`.`create_by`','`ta`.`sort`','`ta`.`del_time`',
            'tb.nick_name as create_by_name',
        ];

        $tb_user_info = BkUserInfoActiveRecord::tableName();
        $result = BkPrivilegeActiveRecord::find()
            ->select($fields)
            ->leftJoin("$tb_user_info as tb",'ta.create_by=tb.user_id')
            ->whereArray(['id'=>$this->id])
            ->asArray()
            ->one();

        if (empty($result)) {
            $this->addError('id', '查询条目不存在');
            return false;
        }


        // 关联角色
        $result['role_ids'] = \QTTX::$app->db
            ->select('role_id')
            ->from(BkRelationRolePrivilegeActiveRecord::tableName())
            ->whereArray(['privilege_id' => $this->id])
            ->where('del_time=0')
            ->column();

        // 获取角色的详细
        if (empty($result['role_ids'])) {
            $result['roles'] = [];
        }else{
            $result['roles'] = BkRoleActiveRecord::find()
                ->select(['id', 'name'])
                ->whereIn('id', $result['role_ids'])
                ->asArray()
                ->all();
        }

        return $result;
    }
}
