<?php
/**
 * File Name: BkPrivilegeActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 17:43:25
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\ActiveRecord;

/**
 * Class BkPrivilegeActiveRecord
 * @package qh4module\rabc\models
 * @description 数据表tbl_project的ActiveRecord模型
 * @property string $id 
 * @property string $parent_id 
 * @property string $id_path 所有父级ID
 * @property string $key 唯一标记
 * @property string $key_path 所有父级标记
 * @property string $name 名称
 * @property string|null $desc 说明
 * @property int $type 类型 1 菜单 2页面元素
 * @property int $level 
 * @property string|null $icon 仅对菜单有效,图标
 * @property string $path 关联的路由
 * @property int $create_time 
 * @property string $create_by 
 * @property int $sort 排序,数字越大越靠前
 * @property int $del_time 
 */
class BkPrivilegeActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%bk_privilege}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "ta";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "id";
    }
}
