<?php
/**
 * File Name: BkRelationRolePrivilegeModel.php
 * Automatically generated by QGC tool
 * @date: 2021-04-23 12:48:25
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\Model;

/**
 * Class BkRelationRolePrivilegeModel
 * @package qh4module\rabc\models
 * @description 数据表tbl_bk_relation_role_privilege的Validate模型
 */
class BkRelationRolePrivilegeModel extends Model
{

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        return [
			[['id', 'del_time'], 'integer'], 
			[['role_id', 'privilege_id'], 'string', ['max' => 64]]
		];
    }

    /**
     * {@inheritDoc}
     */
    public function attributeLangs()
    {
        return [
			'id' => 'ID', 
			'role_id' => '角色', 
			'privilege_id' => '权限'
		];
    }
}
