<?php
/**
 * File Name: BkRelationUserRoleActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 11:12:43
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\ActiveRecord;

/**
 * Class BkRelationUserRoleActiveRecord
 * @package qh4module\rabc\models
 * @description 数据表tbl_project的ActiveRecord模型
 * @property int $id 
 * @property string $user_id 
 * @property string $role_id 
 * @property int $del_time 
 */
class BkRelationUserRoleActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%bk_relation_user_role}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "ta";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "id";
    }
}
