<?php
/**
 * File Name: BkRelationUserRoleModel.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 11:12:58
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\Model;

/**
 * Class BkRelationUserRoleModel
 * @package qh4module\rabc\models
 * @description 数据表tbl_bk_relation_user_role的Validate模型
 */
class BkRelationUserRoleModel extends Model
{

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        return [
			[['id', 'del_time'], 'integer'], 
			[['user_id', 'role_id'], 'string', ['max' => 64]]
		];
    }

    /**
     * {@inheritDoc}
     */
    public function attributeLangs()
    {
        return [
			'id' => 'ID', 
			'user_id' => '用户', 
			'role_id' => '角色'
		];
    }
}
