<?php
/**
 * File Name: BkRelationRolePrivilegeActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-23 12:48:09
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\ActiveRecord;

/**
 * Class BkRelationRolePrivilegeActiveRecord
 * @package qh4module\rabc\models
 * @description 数据表tbl_project的ActiveRecord模型
 * @property int $id 
 * @property string $role_id 
 * @property string $privilege_id 
 * @property int $del_time 
 */
class BkRelationRolePrivilegeActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%bk_relation_role_privilege}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "id";
    }
}
