<?php
/**
 * File Name: BkRoleActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-22 10:37:43
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\ActiveRecord;

/**
 * Class BkRoleActiveRecord
 * @package qh4module\rabc\models
 * @description 数据表tbl_project的ActiveRecord模型
 * @property string $id ID
 * @property string $name 名称
 * @property string|null $desc 说明
 * @property string $create_by 创建人
 * @property int $create_time 创建时间
 * @property int $is_fixed 不可变
 * @property int $del_time 
 */
class BkRoleActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%bk_role}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "ta";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "id";
    }
}
