<?php
/**
 * File Name: BkUserInfoActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-21 10:37:51
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\ActiveRecord;

/**
 * Class BkUserInfoActiveRecord
 * @package qh4module\rabc\models
 * @description 数据表tbl_project的ActiveRecord模型
 * @property string $user_id 
 * @property string|null $nick_name 昵称
 * @property string|null $avatar 头像
 * @property int $gender 1 男 2女
 * @property string|null $birthday 生日
 * @property string|null $description 个人简介
 * @property int $city_id 所在地区
 */
class BkUserInfoActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%bk_user_info}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "ta";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "user_id";
    }
}
