<?php
/**
 * File Name: BkUserInfoModel.php
 * Automatically generated by QGC tool
 * @date: 2021-04-21 10:38:28
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\Model;

/**
 * Class BkUserInfoModel
 * @package qh4module\rabc\models
 * @description 数据表tbl_bk_user_info的Validate模型
 */
class BkUserInfoModel extends Model
{

    /**
     * {@inheritDoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'string', ['max' => 64]],
            [['nick_name'], 'string', ['max' => 20]],
            [['avatar'], 'string', ['max' => 500]],
            [['city_id'], 'integer'],
            [['birthday'], 'match', 'pattern' => '/\d+-\d+-\d+/'],
            [['description'], 'string', ['max' => 1000]],
            [['gender'], 'in', 'range' => [0, 1, 2]],
        ];
    }

    /**
     * {@inheritDoc}
     */
    public function attributeLangs()
    {
        return [
            'user_id' => '用户ID',
            'nick_name' => '昵称',
            'avatar' => '头像',
            'gender' => '性别',
            'birthday' => '生日',
            'description' => '个人简介',
            'city_id' => '所在地区'
        ];
    }
}
