<?php
/**
 * File Name: BkUserActiveRecord.php
 * Automatically generated by QGC tool
 * @date: 2021-04-21 10:37:43
 * @version: 4.0.4
 */

namespace qh4module\rabc\models;


use qttx\web\ActiveRecord;

/**
 * Class BkUserActiveRecord
 * @package qh4module\rabc\models
 * @description 数据表tbl_project的ActiveRecord模型
 * @property string $id 
 * @property string|null $account 账号
 * @property string|null $mobile 手机号
 * @property string|null $email 邮箱
 * @property string|null $password 密码
 * @property string|null $salt 密码混淆随机数
 * @property string $create_by 创建人
 * @property int $create_time 创建时间
 * @property string|null $wechat_unionid 
 * @property string|null $wechat_openid 
 * @property string|null $qq_id 
 * @property string|null $alipay_id 
 * @property string|null $weibo_id 
 * @property string|null $apple_id 
 * @property int $state 1正常2禁止登录3账号异常
 * @property int $del_time 
 */
class BkUserActiveRecord extends ActiveRecord
{
    /**
     * @var string 数据表名
     */
    protected static $table_name = "{{%bk_user}}";

    /**
     * @var string 数据表别名
     */
    protected static $table_alias = "ta";

    /**
     * 返回数据表的主键
     * @return string
     */
    static function primaryKey()
    {
        return "id";
    }
}
